

version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smm
      POSTGRES_PASSWORD: vrag
      POSTGRES_DB: furnace_history




