name:
  Django Testing and Deploy

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check updates
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Activate environments
        run: python -m venv .venv

      - name: setup libs
        run: |
          pip install --upgrade pip |
          pip install -r requirements.txt

      - name: Linting main
        run: flake8 main.py

      - name: Linting classes
        run: flake8 classes

      - name: Linting models
        run: flake8 models


